on: [push] 

jobs: 

  build: 

    runs-on: ubuntu-latest 

    steps: 

    - uses: actions/checkout@master 

     

    # Connect to Azure Container registry (ACR) 

    - uses: azure/docker-login@v1 

      with: 

        login-server: demoaksgithub.azurecr.io 

        username: ${{ secrets.REGISTRY_USERNAME }}  

        password: ${{ secrets.REGISTRY_PASSWORD }} 

     

    # Docker build and push to a Azure Container registry (ACR) 

    - run: | 
        docker build . -t demoaksgithub.azurecr.io/k8sdemo:${{ github.sha }} 
        docker push demoaksgithub.azurecr.io/k8sdemo:${{ github.sha }} 
     
    # Set the target AKS cluster.  

    - uses: azure/aks-set-context@v1 

      with: 

        creds: '${{ secrets.AZURE_CREDENTIALS }}' 

        cluster-name: AKSdemo 

        resource-group: shirispire 

    # Deploy Artifactory
    - uses: jfrog/setup-jfrog-cli@v1 
    - run: |
       jfrog rt config --interactive=false --enc-password=true --url=https://batelt.jfrog.io/batelt/ --user=admin --password=AKCp5dK4h1kFqpKNApsy63cnHFeE5LHwX5evf6dg9uEuYdHxbHfUdiLcjJoDQxxxcrF81mS4m
       
     

