on: [push]

env:
  REGISTRY_NAME: atulmakshelm
  REGISTRY_USERNAME: my-registry-username
  CLUSTER_NAME: brendan-demo
  CLUSTER_RESOURCE_GROUP: brendan-demo
  NAMESPACE: default

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

     # Set the target Azure Kubernetes Service (AKS) cluster. 
    - uses: azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: ${{ env.CLUSTER_NAME }}
        resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}
    
    # Create namespace if doesn't exist
    - run: |
        kubectl create namespace ${{ env.NAMESPACE }} --dry-run -o json | kubectl apply -f -
    
    # Create imagepullsecret for Azure Container registry (ACR)
    - uses: azure/k8s-create-secret@v1
      with:
        container-registry-url: ${{ env.REGISTRY_NAME }}.azurecr.io
        container-registry-username: ${{ secrets.REGISTRY_USERNAME }}
        container-registry-password: ${{ secrets.REGISTRY_PASSWORD }}
        secret-name: ${{ env.REGISTRY_NAME }}-registry-connection
        namespace: ${{ env.NAMESPACE }}
    
    # Deploy app to AKS
    - uses: azure/k8s-deploy@deploymentstrategy
      with:
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          ${{ env.REGISTRY_NAME }}.azurecr.io/k8sdemo:50fefd6c7fba86b9a9dffaf20598c50483592f17
        imagepullsecrets: |
          ${{ env.REGISTRY_NAME }}-registry-connection
        namespace: ${{ env.NAMESPACE }}
        deployment-strategy: CANARY
        trafficSplitMethod: pod
        percentage: 20

    - run: |
        kubectl get services -n demo
